title: Student
description: "Class of 2026"
owner_name: Arnav Mittal
github_username: Arnav210
github_repo: "Arnav_2026" 
baseurl: "/Arnav_2026" 
future: true
remote_theme: jekyll/minima
minima:
  skin: solarized-dark
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
header_pages:
  - documentation/home.md
  - navigation/blog.md
  - navigation/search.md
  # - navigation/about.md
  ###
